import type { NextPage } from 'next'
import Head from 'next/head'
const Search: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Search - Search the Ikhaos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Search
